//
//  SettingsModel.swift
//  iOS3-HW12-Fedyshin Matvey
//
//  Created by matt_spb on 08.01.2022.
//

import UIKit

final class SettingsModel {

    func createModels() -> [Section] {
        return [
            Section(options: [
                SettingsOption(cellType: .switchCell,
                               title: "Airplane Mode",
                               iconName: "airplane",
                               backgroundColor: .systemOrange,
                               detailInfo: nil,
                               isOn: false),
                SettingsOption(cellType: .detailCell,
                               title: "Wi-Fi",
                               iconName: "wifi",
                               backgroundColor: .systemBlue,
                               detailInfo: "Home_Wi-Fi",
                               isOn: nil),
                SettingsOption(cellType: .detailCell,
                               title: "Bluetooth",
                               iconName: "bluetooth",
                               backgroundColor: .systemBlue,
                               detailInfo: "On",
                               isOn: nil),
                SettingsOption(cellType: .regularCell,
                               title: "Mobile Data",
                               iconName: "antenna.radiowaves.left.and.right",
                               backgroundColor: .systemGreen,
                               detailInfo: nil,
                               isOn: nil),
                SettingsOption(cellType: .regularCell,
                               title: "Personal Hotspot",
                               iconName: "personalhotspot",
                               backgroundColor: .systemGreen,
                               detailInfo: nil,
                               isOn: nil)
            ]),
            Section(options: [
                SettingsOption(cellType: .regularCell,
                               title: "Notifications",
                               iconName: "bell.badge.fill",
                               backgroundColor: .systemRed,
                               detailInfo: nil,
                               isOn: nil),
                SettingsOption(cellType: .regularCell,
                               title: "Sounds & Haptics",
                               iconName: "speaker.wave.3.fill",
                               backgroundColor: .systemRed,
                               detailInfo: nil,
                               isOn: nil),
                SettingsOption(cellType: .regularCell,
                               title: "Focus",
                               iconName: "moon.fill",
                               backgroundColor: .systemPurple,
                               detailInfo: nil,
                               isOn: nil),
                SettingsOption(cellType: .regularCell,
                               title: "Screen Time",
                               iconName: "hourglass",
                               backgroundColor: .systemPurple,
                               detailInfo: nil,
                               isOn: nil)
            ]),
            Section(options: [
                SettingsOption(cellType: .regularCell,
                               title: "General",
                               iconName: "gear",
                               backgroundColor: .systemGray,
                               detailInfo: nil,
                               isOn: nil),
                SettingsOption(cellType: .regularCell,
                               title: "Control Centre",
                               iconName: "switch.2",
                               backgroundColor: .systemGray,
                               detailInfo: nil,
                               isOn: nil),
                SettingsOption(cellType: .regularCell,
                               title: "Display & Brightness",
                               iconName: "textformat.size",
                               backgroundColor: .systemBlue,
                               detailInfo: nil,
                               isOn: nil),
                SettingsOption(cellType: .regularCell,
                               title: "Home Screen",
                               iconName: "apps.ipad.landscape",
                               backgroundColor: #colorLiteral(red: 0.2196078449, green: 0.007843137719, blue: 0.8549019694, alpha: 1),
                               detailInfo: nil,
                               isOn: nil),
                SettingsOption(cellType: .regularCell,
                               title: "Accessibility",
                               iconName: "figure.walk.circle",
                               backgroundColor: .systemBlue,
                               detailInfo: nil,
                               isOn: nil),
                SettingsOption(cellType: .regularCell,
                               title: "Wallpaper",
                               iconName: "paperplane.circle",
                               backgroundColor: #colorLiteral(red: 0.4620226622, green: 0.8382837176, blue: 1, alpha: 1),
                               detailInfo: nil,
                               isOn: nil),
                SettingsOption(cellType: .regularCell,
                               title: "Face ID & Passcode",
                               iconName: "faceid",
                               backgroundColor: .systemGreen,
                               detailInfo: nil,
                               isOn: nil),
                SettingsOption(cellType: .regularCell,
                               title: "Exposure Notifications",
                               iconName: "sun.min.fill",
                               backgroundColor: #colorLiteral(red: 0.9764705896, green: 0.850980401, blue: 0.5490196347, alpha: 1),
                               detailInfo: nil,
                               isOn: nil),
                SettingsOption(cellType: .regularCell,
                               title: "Battery",
                               iconName: "battery.100",
                               backgroundColor: .systemGreen,
                               detailInfo: nil,
                               isOn: nil),
                SettingsOption(cellType: .regularCell,
                               title: "Privacy",
                               iconName: "hand.raised.fill",
                               backgroundColor: .systemBlue,
                               detailInfo: nil,
                               isOn: nil),
            ]),
            Section(options: [
                SettingsOption(cellType: .regularCell,
                               title: "App Store",
                               iconName: "applelogo",
                               backgroundColor: .systemBlue,
                               detailInfo: nil,
                               isOn: nil),
                SettingsOption(cellType: .regularCell,
                               title: "Wallet & Apple Pay",
                               iconName: "creditcard.fill",
                               backgroundColor: .systemGray2,
                               detailInfo: nil,
                               isOn: nil)
            ])
        ]
    }
}
